### ISSUE TITLE
Ignore api.php requests

### ISSUE THREAD

**Issue by Seb35** [jeanbaptisteb/classic_wikipedia#3]
It’s a detail, but it would be great to ignore the requests `/w/api.php` on all wikis. The parameter `useskin=vector` is not recognised by the API and MediaWiki emits a warning ([example](https://en.wikipedia.org/w/api.php?action=query&meta=siteinfo&useskin=vector)).

PS: thanks a lot for this extension!

**Comment by jeanbaptisteb** [comment]
@Seb35 Thanks for the feedback, I'll have a look at it soon. I'm super busy these days but unless I missed something, it shouldn't be complicated at all to fix. I'm confident I'll have it fixed in a couple of weeks. 

If by any chance you know of other exceptions like this, please let me know, I'll fix them at the same time. By the way, if you speak French, we can discuss in this language if you prefer.

Just as a reminder for myself (or if someone else wants to test it before I deploy the fix), in the `background.js` file, adding the string `/w\/api.php/` in the `var excludedUrls ` array should fix the issue very simply, such as:

```
var excludedUrls = [/(www|nostalgia|[.]m)[.]wikipedia[.]org/, /www[.]wiktionary[.]org/, 
/(.*[.]m[.]|m[.])/, 
/.*[.]m[.]wikimedia[.]org/,
/commons[.]m[.]wikimedia[.]org/,
/mobileaction=toggle_view_mobile/,
/w\/api.php/
]
```

**Comment by jeanbaptisteb** [comment]
@Seb35 The bug is (hopefully) corrected. I submitted the new version of the module on the Firefox developer hub, and the update should be effective in 24 hours. It was a bit more complicated than what I thought. Tell me if it works as expected, or if it still requires some modifications.

**Comment by jeanbaptisteb** [comment]
@Seb35 It seems that the new version is already available on the Firefox addins catalog, you don't even have to wait 24 hours if you want to try and update it.

**Comment by jeanbaptisteb** [comment]
@Seb35 Without negative feedback after two weeks of deployment, I consider the issue as solved, but if you encounter some problems again, feel free to reopen the discussion.

**Comment by Seb35** [comment]
Ah, I missed the previous notifications, sorry. And indeed the version 1.5.2 works well, thanks a lot!
